name: build-test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    container: node:latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5    
    steps:
    - name: Install PostgreSQL client
      run: |   
        apt-get update
        apt-get install --yes postgresql-client
    - name: Checkout peon        
      uses: actions/checkout@v2
      with:
        repository: uka17/peon
        path: peon
    
    - name: Checkout peon-web
      uses: actions/checkout@v2
      with:
        repository: uka17/peon-web
        path: peon-web
    - name: Create peon DB
      run: psql -h postgres -p 5432 -U postgres -c 'create database peon' 
      env:
          PGPASSWORD: test
    - name: Structure of peon DB
      run: psql -h postgres -p 5432 -U postgres -d peon -f "$GITHUB_WORKSPACE/peon/dev_scripts/peon.sql"
      env:
          PGPASSWORD: test      
    - name: Populate refs of peon DB
      run: psql -h postgres -p 5432 -U postgres -d peon -f "$GITHUB_WORKSPACE/peon/dev_scripts/refsCreation.sql"      
      env:
          PGPASSWORD: test      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: peon/package-lock.json
    - name: Install, build and test peon
      run: npm ci
      working-directory: ./peon
    - run: npm run build --if-present
      working-directory: ./peon
    - run: npm test
      working-directory: ./peon
      env:
        DB_CONNECTION: "postgresql://postgres:test@postgres:5432/peon"  
        PORT: 8080  
        APP_ENV: "qa"
        TEST_MODE: "quick"
    - run: npm run coverage
      working-directory: ./peon
      env:
        DB_CONNECTION: "postgresql://postgres:test@postgres:5432/peon"  
        PORT: 8080  
        APP_ENV: "qa"
    - name: Coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        base-path: ./peon        
        path-to-lcov: ${{ github.workspace }}/peon/coverage/lcov.info
    - name: Install, build and test web-peon
      run: npm ci
      working-directory: ./peon-web    
    - name: Launch peon-api
      run: npm run dev-srv &
      working-directory: ./peon
      env:
        DB_CONNECTION: "postgresql://postgres:test@postgres:5432/peon"  
        PORT: 8080  
        APP_ENV: "qa"
    - name: Launch web-peon
      run: npm run start &
      working-directory: ./peon-web
    - name: E2E tests
      run: npm run ntest
      working-directory: ./peon-web      
