name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    container: node:10.18-jessie
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5    
    steps:
    - name: Install psql
      run: sudo apt-get install -y postgresql-client
    - uses: actions/checkout@v2
    - name: Create peon DB
      run: psql -h postgres -p 5432 -U postgres -c 'create database peon' 
    - name: Structure of peon DB
      run: psql -h postgres -p 5432 -U postgres -d peon -f "./dev_scripts/peon.sql"
    - name: Populate refs of peon DB
      run: psql -h postgres -p 5432 -U postgres -d peon -f "./dev_scripts/refsCreation.sql"      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
